language: c

# Use Ubuntu 14.04
sudo: required
dist: trusty

env:
  matrix:
    - USE_DOTNET_CLI_VERSION: 1.0.0.001461

install:
  # download install script from dotnet/cli repo
  - mkdir -p "scripts/obtain"
  - wget -O "./scripts/obtain/install.sh" "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.sh"
  # install a specific dotnet/cli version in DOTNET_INSTALL_DIR directory
  - chmod +x ./scripts/obtain/install.sh
  - ./scripts/obtain/install.sh --channel beta -version $USE_DOTNET_CLI_VERSION --destination "$(pwd)/.dotnet"
  # show current dotnet info
  - echo "Using dotnet '$(which dotnet)'"
  - dotnet --version

script: 
  - dotnet restore
  # build dotnet-fssrgen
  - cd src/dotnet-fssrgen
  - dotnet build
